#name = input("What is your name? ")
#a = input("What is your address? ")
#b = input("What is your credit card number? ")
#c = input("When is noone home? ")
#d = input("Do you have a girl? ")
#e = input("Where do you keep your keys? ")
#f = input("What is the code for your safe? ")
#g = input("What is your dogs name? ")
#h = input("What is your security system? ")
#i = input("What are your passwords? ")
#j = input("Do you still have all your organs? ")
#k = print("Thank you for your private info. It will be used against you.")
#l = print("Please go to this link: https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley. ")
stoleninfo=[(input("What is your name? "),input("What is your address? "),input("What is your credit card number? "),input("When is noone home? "),input("Do you have a girl? "),input("Where do you keep your keys? "),input("What is the code for your safe? "),input("What is your dogs name? "),input("What is your security system? "),input("What are your passwords? "),input("Do you still have all your organs? "),print("Thank you for your private info. It will be used against you."),print("Please go to this link: https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley. "))]
