import time
HP=100

print('\u001b[31m')
print("Hello.")
time.sleep(0.5)
name=input("What shall be your name, good sir? ")
print(name + "?")
time.sleep(1)
yesno=input("Are you sure? ")
if(yesno=="yes" or  yesno=="Yes" or yesno=="Yes." or yesno=="yes."):
    time.sleep(1)
    print("Then enter, " + name + ".")
    time.sleep(1)
    print(' \u001b[32m')
    print("Hello " + name + ". I am Roran, the leader of the Varden,")
    print("                    a group dedicated to protecting the dragons from evil spirits.")
    time.sleep(3)
    print("Roran: The four spirits have stolen the last dragon egg in this dimension. We need you to help us take it back.")
    time.sleep(1)
    print("       These spirits have elemental powers; earth, water, air, and fire.")
    time.sleep(6)
    print('\u001b[34m')
    print(name + ": What type of powers exactly?")
    time.sleep(1)
    print(' \u001b[32m')
    print("Roran: They each have three attacks. One super attack, and one short range and one long range.")
    time.sleep(4)
    print("       Earth has pebble gun, rock slam and super earth wave. Water has ice shard, water bash, and super whirlpool.")
    time.sleep(4)
    print("       Air has air arrow, wind axe, and super tornado. Fire has fireball, flame blade, and super flame shockwave.")
    time.sleep(4)
    print('\u001b[34m')
    print(name + ": Well then what do I have?")
    time.sleep(1)
    print(' \u001b[32m')
    print("Roran: We will give you a magical sword and shield,")
    time.sleep(2)
    print("       and imbue you with magic so you have a special attack of your own.")
    time.sleep(2)
    print("       You will only have two attacks, but a defense also, which the spirits do not.")
    time.sleep(1.75)
    print("       These will be flaming arrow, earth air swing, and super water shield.")
    time.sleep(5)
    print('\u001b[34m')
    print(name + ": Alright. Then I will attempt to get it back, Roran, leader of the Varden.")
    time.sleep(2)
    print('\u001b[33m')
    print("*walks away purposefully*")
    time.sleep(1)
    print('\u001b[35m')
    print("walking")
    time.sleep(0.25)
    print("walking")
    time.sleep(0.25)
    print("walking")
    time.sleep(0.25)
    print("walking")
    time.sleep(0.25)
    print("walking")
    time.sleep(0.25)
    print('\u001b[32m')
    print("Roran: Congratulations " + name + ". You have arrived at the first battlefield")
    time.sleep(2.75)
    print("       on your long journey.")
    time.sleep(1.5)
    print('\u001b[34m')
    print(name + ": Roran? Where are you?")
    time.sleep(1.25)
    print('\u001b[30m' + name + ": "'\u001b[34m' + "Have you come with me? Or are you spying on me?")
    time.sleep(2)
    print('\u001b[32m')
    print("Roran: No. Not spying, and I'm not here with you.")
    time.sleep(1)
    print("       Just watching you through magic, so that")
    time.sleep(1)
    print("       we may offer advice and warnings if")
    time.sleep(1)
    print("       someone is sneaking up on you.")
    time.sleep(1)
    print("       Watch out! The fight has started . . .")
    time.sleep(1)
    print('\u001b[33m')
    print("voice fades away")
    time.sleep(1)
    print("spirit uses pebble gun")
    print("miss")
    time.sleep(1)
    print('\u001b[37m')
    HP = 100
    print("You now have " + str(HP) + "/100 HP")
    time.sleep(1)
    HPsp1=50
    while(int(HPsp1)>0) and int(HP)>0:
        attack = int(input("You can use flaming arrow (1), earth air swing (2), or super water shield (3). "))
        if (attack==1):
            print('\u001b[33m')
            print("You use flaming arrow.")
            print('\u001b[37m')
            HPsp1 = int(HPsp1)-25
            print("The spirit now has " + str(HPsp1) + "/50 HP")
            print('\u001b[33m')
            print("The spirit uses rock slam.")
            HP = int(HP)-40
            print('\u001b[37m')
            print("You now have " + str(HP) + "/100 HP.")
            time.sleep(1)
        if (attack==2):
            print('\u001b[33m')
            print("You use earth air swing.")
            print('\u001b[37m')
            HPsp1 = int(HPsp1) - 50
            print("The spirit now has "+ str(HPsp1) + "/50 HP")
            print('\u001b[33m')
            print("The spirit uses super earth wave.")
            print('\u001b[37m')
            HP = int(HP)-45
            print("You now have " + str(HP) + "/100 HP")
        if (attack == 3):
            print('\u001b[33m')
            print("You use super water shield.")
            print('\u001b[33m')
            print("The spirit uses super earth wave.")
            print('\u001b[37m')
            HP = int(HP)-0
            print("You still have " + str(HP) + "/100 HP")
            time.sleep(1)
    if int(HP)==0 :
        print('\u001b[36m')
        print("You have died. :(")
        exit()
    print('\u001b[32m')
    print("Roran: Well done! You did it!")
    time.sleep(1.25)
    print("       Carry on to the next place.")
    def function_name(fightquestion):
        while (int(HPsp1) > 0) and int(HP) > 0:
            attack = int(input("You can use flaming arrow (1), earth air swing (2), or super water shield (3). "))
        return

